apiVersion: apps/v1
kind: Deployment
metadata:
  name: softiwa-ui-prod #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  namespace: softiwa-ui      
  labels:
    app: softiwa-ui-prod
spec:
  replicas: 1 #The number of pods to be created in the 
   #Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: softiwa-ui-prod
  template:
    metadata:
      labels:
        app: softiwa-ui-prod
      annotations:
        kubernetes.io/change-cause: "Updated deployment"  
    spec:
      containers:
      - name: softiwa-ui-prod #The name of the react.js application container
        #The Docker image for building the React.js application container
        image: iamlavityagi/softiwa-ui-prod:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 #The port for the React.js application container